# Generated by Django 5.2.16 on 2026-07-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='stoke',
            new_name='stock',
        ),
    ]
