# Generated by Django 5.2.16 on 2026-07-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_stoke_productmodel_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
